### ISSUE TITLE
Hi my bro

### ISSUE THREAD

**Issue by Ninjacoderhsi** [Rosemoe/CodeEditor#117]
![Screenshot_۲۰۲۱۱۱۰۱-۲۰۴۴۲۸_ZArchiver Pro](https://user-images.githubusercontent.com/89408667/139712840-5cd938b3-5766-4c31-b906-4e975590ff51.jpg)
I tried all the themes and languages ​​but what is the reason for not running any of them?
Soon fixed?
(Library textmate)

**Comment by Coyamo** [comment]
Hi.
1. Textmate theme must be used with TM language. 
2. Not all themes are supported, because tm4e is transplanted based on the old version of vscode-textmate. At present, tmtheme and tmlanguage of VSC may not be loaded. If you encounter something that cannot be loaded, it is recommended to try other...

**Comment by Ninjacoderhsi** [comment]
Hi my try edit theme (tm) and edit color and ....
Ples send msg to telgram https://t.me/Dark_stile so help me

**Comment by Coyamo** [comment]
> Hi my try edit theme (tm) and edit color and .... Ples send msg to telgram https://t.me/Dark_stile so help me

I just add Textmate to the project and use it. I don't know how to customize rule files. There's nothing I can do about it. Maybe you can see how other available rules are written ...

**Comment by Ninjacoderhsi** [comment]
Send id telagram me
