### ISSUE TITLE
[Feature] Add Wordwrap

### ISSUE THREAD

**Issue by MrIkso** [Rosemoe/CodeEditor#9]
Hello, the good idea was to create such a editor. But it does not have enough, the wordwrap content

**Comment by Rosemoe** [comment]
Thanks for the advice!
It is really a good idea and almost all editors implement this. But some editors did not, such as AIDE's code editor. I did not add wordwrap because of that.
Wordwrap costs quite time to do when the  text is long. I've long being thinking of how to optimize.
I'll add this in a future version.
Because it is a big change to current editor structure, it may be a long time to make.

**Comment by Rosemoe** [comment]
Now I am working on wordwrap.
It is supposed to be finished within a week.
